{% set name = "flowsom" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/saeyslab/FlowSOM_Python/archive/v{{ version }}.tar.gz
  sha256: 0ff78a6ad4c9e2c2152d64e1b1922e156f41ccb23fb4b7f03d10833f027ecaa8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - pip
  run:
    - python >=3.9
    - mudata
    - numpy
    - matplotlib-base
    - pandas
    - scipy
    - readfcs
    - pytometry
    - scikit-learn
    - python-igraph
    - session-info
    - numba
    - scanpy
    - seaborn
    - anndata
    - loguru

test:
  imports:
    - flowsom
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/saeyslab/FlowSOM_Python
  summary: The complete FlowSOM package known from R, now available in Python!
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - berombau
