{% set name = "flowsom" %}
{% set version = "0.2.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/saeyslab/FlowSOM_Python/archive/v{{ version }}.tar.gz
  sha256: e04738deccad63f69501025057f0b6559a5d8b9c12d277e894044ba3c517d122

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - mudata
    - numpy
    - matplotlib-base
    - pandas
    - scipy
    - readfcs
    - scikit-learn
    - python-igraph
    - session-info
    - numba
    - scanpy
    - seaborn
    - anndata
    - loguru

test:
  imports:
    - flowsom
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/saeyslab/FlowSOM_Python
  summary: The complete FlowSOM package known from R, now available in Python!
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - berombau
